### ISSUE TITLE
Chat clear button

### ISSUE THREAD

**Issue by wolvenhaven** [webbage/webbage.chat#68]
Create a button that clears the chat on the screen

**Comment by Kwayzu** [comment]
The refresh/F5 button clears the screen :P

**Comment by Kwayzu** [comment]
Clear button has been added.  I submitted a commit let me know if I need to follow a different process on submitting changes.  I also put the mute <i> inside a button i couldn't figure out how to position it otherwise.

**Comment by bamblack** [comment]
Code looks pretty good, I am however going to revert it due to 1. Shouldn't push directly to master (not your fault, I didn't tell you) 2. Don't do work unless we have an issue against it (bot comamnds, again, not your fault) and 3. No DOM manipulation in angular controllers. The `$scope.messages = [];` was all that was needed.

**Comment by bamblack** [comment]
Merged to 2.2.1 in https://github.com/webbage/webbage.chat/pull/78

**Comment by bamblack** [comment]
Merged to dev in https://github.com/webbage/webbage.chat/pull/79

**Comment by bamblack** [comment]
Merged to master in https://github.com/webbage/webbage.chat/pull/87
